### ISSUE TITLE
Add Refresh/Redraw method for updating data

### ISSUE THREAD

**Issue by nathanh2011** [JustinWilkinson/DataTables.Blazor#18]
Firstly, thanks for this great project as it is exactly what I was looking for to bring datatables into Blazor.

I found an issue that when initially loading the datatable it runs as expected but if I wanted to change/modify/update the data, it did not seem to take effect, specifically by changing the DOM or updating the data object.

To replicate the issue, using your demo project I used the `WeatherDataset` Dataset as the source of data for the object and DOM display options. I modified the DOM table as below:

```
<DataTable @ref="WeatherDomTable" Id="MyTableDomSourced" Class="table table-striped table-bordered w-100">
	<thead>
		<tr>
			<th>Date</th>
			<th>Temp. (C)</th>
			<th>Summary</th>
		</tr>
	</thead>
	<tbody>
		@foreach (Weather w in WeatherDataset)
	{
			<tr>
				<td>@w.Date.ToString("yyyy-MM-dd")</td>
				<td>@w.TemperatureC</td>
				<td>@w.Summary</td>
			</tr>
	}
	</tbody>
</DataTable>
```

I then created a button and function that would generate a random list of `Weather` objects and assign them to the `WeatherDataset` and call `StateHasChanged`. The DOM table would update the HTML but the datatable would not recognise the change and just show all the rows but not paginate, search or show the correct total number of items. The object table would not update at all until I navigated to another tab and back again.

I found a solution by adding the following function to the Datatables.Blazor\Datatable.razor page:

```
public async Task RefreshTable() {
	await Datatables.DestroyAsync(_tableReference);
	await Datatables.InitialiseAsync(_tableReference, DataTableOptions.FromComponent(this));
	await InvokeAsync(StateHasChanged);
}
```

So then I reference your datatable instance on my page, then when I update the `WeatherDataset` I then call `WeatherDomTable.Refresh()` and the table seems to update correctly.

I was wondering if this change could be added to main branch of this project or if there is any better way to update data and have it displayed.

To give some background on my project, I have a timer that will poll a database every 2 minutes and I need to update the datatable accordingly.

**Comment by soenneker** [comment]
I agree this is not as intuitive as it should be.

Another way to accomplish what you're talking about is double rendering, forcing the DateTable to reinitialize.

```csharp
@if (_dataSet != null)
{
  <DataTable>...
}

@code {
  WeatherDataset? _dataSet;
  
  void RefreshTable()
  {
      _dataSet = null;
      StateHasChanged();
      
      _dataSet = incoming change 
      StateHasChanged();
  }

}
```

This isn't as optimized as it can be. I guess I'd prefer to just say to the datatable reference `.ReInitialize()` once the data has changed.

@JustinWilkinson have you run into this too?

**Comment by JustinWilkinson** [comment]
The table's only initialized during `firstRender` in `OnAfterRenderAsync` and currently can't be initialized again. The DOM source issue is a quirky one, because the `StateHasChanged()` doesn't actually trigger the blazor lifecycle on the `DataTable` component - it doesn't realize that the `ChildContent` has been modified.
I've done some digging, and it looks like this can be sorted by using `SetParametersAsync` will add a couple of new features, to expose a manual reinitialize, an ajax/data reload and an `AutoReload` flag that can be enabled to trigger when the table re-renders.

**Comment by JustinWilkinson** [comment]
@nathanh2011 @soenneker - the above PR addresses this issue. For Ajax or Data sourced tables it's got a fast reload capability, for DOM sourced data we're forced to destroy and re-initialize the datatable.
The reload and re-initialize capabilities are publicly exposed, and I have added an `AutoReload` flag as a quality of life feature for simpler use cases. 
I've added a sample to the demo project, which probably wants splitting into pages at some point now there are so many tabs...

If you spot anything obviously wrong let me know, otherwise I'll get that merged, and it'll be available in v3.2.0 of the package.

**Comment by nathanh2011** [comment]
@JustinWilkinson I just checked your changes, both in the demo project and incorporating into my own and it works perfectly for DOM tables. I didn't check for the object one, but I assume as long as I call StateHasChanged that auto reload will fire?

Otherwise, very nice work, you are a king amongst men!

**Comment by JustinWilkinson** [comment]
@nathanh2011 - for the `Data` parameter it should re-render automatically [when the parameters are modified](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-6.0#rendering-conventions-for-componentbase).

I'll merge this for you now.
